#!/bin/bash
echo "start cal"
echo "cal import num1 ope num2"
echo "fin is END"
while :
do
    read -p "enter number " num1 ope num2
    if [ "$num1" = "[0-9]*$" && "$num2" = "[0-9]*$" ] ; then 
        if [ "$ope" = + ] ; then 
            echo $num1+$num2=$(( $num1 + $num2 ))
        elif [ "$ope" = - ] ; then
            echo $num1-$num2=$(( $num1 - $num2 ))
        elif [ "$ope" = \* ] ; then
            echo $num1*$num2=$(( $num1 \* $num2 ))
        elif [ "$ope" = / ] ; then
            count=$(( $num1 / $num2 ))
            amari=$(( $num1 % $num2 ))
            if [ $amari -eq 0 ] ; then
                echo $num1/$num2=$count
            else
                echo $num1/$num2=$count ... $amari
            fi
        fi
    else
        if [[ $num1 = "END" ]] ; then
            break
        else
            echo "AAA"
        fi
    fi
done
