#!/bin/bash
for ((;;))
do
    read -p "now time" A
    if [$A -ge 5 -a $A -le 20] ; then
        echo "おはよう"
    elif [$A -ge 11 -a $A -le 15 ] ; then 
        echo "こんにちわ"
    elif [ $A -ge 16 -a $A -le 20 ] ; then
        echo "こんばんわ"
    elif [ $A -ge 21 -a $A -le 24 ] ; then 
        echo "おやすみ"
    else
        "0時から24時までで入力してください"
    fi

    read -p "終了しますか" B
    if [ $B = yes ] ; then
        break
    fi
done