#!/bin/bash
echo "start cal"
echo "cal import num1 ope num2"
echo "fin is END"
while : 
do
read -p "enter number:" num1 ope num2
if  expr "$num1" : "[0-9]*$" >&/dev/null || "$num2" : "[0-9]*$" >&/dev/null ; then
    case "$ope" in
        + ) 
            count=$(( $num1 + $num2 ))
            echo "$num1+$num2=$count" ;;
        - ) 
            count=$(( $num1 - $num2 ))
            echo "$num1-$num2=$count" ;;
        \* ) 
            count=$(( $num1 * $num2 )) 
            echo "$num1*$num2=$count" ;; 
        / )
            count=$(( $num1 / $num2 ))
            amari=$(( $num1 % $num2 ))
        if [ $amari -eq 0 ] ; then
                echo "$num1/$num2=$count"
            else
                echo "$num1/$num2=$count ... $amari"
            fi ;;
    esac
else
    case "$num1" in
        "END") break ;;
        *    ) echo "AAA" ;;
    esac
fi
done
